{{ if and (ne .Release.Namespace "prod") (ne .Release.Namespace "dev") }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  annotations:
    replicator.v1.mittwald.de/replicate-from: dev/aws-credentials    
data: {}
{{ end }}