apiVersion: v1
kind: Secret
metadata:
  name: primeintellect-credentials
  annotations:
    {{ if eq .Release.Namespace "prod" }}
    replicator.v1.mittwald.de/replicate-from: skypilot/primeintellect-credentials
    {{ else }}
    replicator.v1.mittwald.de/replicate-from: skypilot-dev/primeintellect-credentials
    {{ end }}
data: {}