{{ if and (ne .Release.Namespace "prod") (ne .Release.Namespace "dev") }}
apiVersion: v1
kind: Secret
metadata:
  name: lambda-credentials
  annotations:
    replicator.v1.mittwald.de/replicate-from: dev/lambda-credentials
data: {}
{{ end }}
