{{ if ne .Release.Namespace "prod" }}
apiVersion: v1
kind: Secret
metadata:
  name: vast-credentials
  annotations:
    replicator.v1.mittwald.de/replicate-from: dev/vast-credentials
data: {}
{{ end }}
