apiVersion: v1
kind: Secret
metadata:
  name: vast-credentials
  annotations:
    {{ if .eq .Release.Namespace "prod" }}
    replicator.v1.mittwald.de/replicate-from: skypilot/vast-credentials
    {{ else }}
    replicator.v1.mittwald.de/replicate-from: skypilot-dev/vast-credentials
    {{ end }}
data: {}
