apiVersion: v1
kind: Secret
metadata:
  name: cluster-credentials
  annotations:
    {{ if .eq .Release.Namespace "prod" }}
    replicator.v1.mittwald.de/replicate-from: skypilot/cluster-credentials
    {{ else }}
    replicator.v1.mittwald.de/replicate-from: skypilot-dev/cluster-credentials
    {{ end }}
data: {}