apiVersion: v1
kind: Secret
metadata:
  name: lambda-credentials
  annotations:
    {{ if .eq .Release.Namespace "prod" }}
    replicator.v1.mittwald.de/replicate-from: skypilot/lambda-credentials
    {{ else }}
    replicator.v1.mittwald.de/replicate-from: skypilot-dev/lambda-credentials
    {{ end }}
data: {}
