apiVersion: v1
kind: Secret
metadata:
  name: nebius-credentials
  annotations:
    {{ if eq .Release.Namespace "prod" }}
    replicator.v1.mittwald.de/replicate-from: skypilot/nebius-credentials
    {{ else }}
    replicator.v1.mittwald.de/replicate-from: skypilot-dev/nebius-credentials
    {{ end }}
data: {}
