apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  annotations:
    {{ if eq .Release.Namespace "prod" }}
    replicator.v1.mittwald.de/replicate-from: skypilot/gcp-credentials
    {{ else }}
    replicator.v1.mittwald.de/replicate-from: skypilot-dev/gcp-credentials
    {{ end }}
data: {}
