{{ if ne .Release.Namespace "prod" }}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  annotations:
    replicator.v1.mittwald.de/replicate-from: dev/gcp-credentials
data: {}
{{ end }}
