apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-credentials
  annotations:
    {{ if .eq .Release.Namespace "prod" }}
    replicator.v1.mittwald.de/replicate-from: skypilot/digitalocean-credentials
    {{ else }}
    replicator.v1.mittwald.de/replicate-from: skypilot-dev/digitalocean-credentials
    {{ end }}
data: {}
