{{ if ne .Release.Namespace "prod" }}
apiVersion: v1
kind: Secret
metadata:
  name: primeintellect-credentials
  annotations:
    replicator.v1.mittwald.de/replicate-from: dev/primeintellect-credentials
data: {}
{{ end }}
