apiVersion: v1
kind: Secret
metadata:
  name: oci-credentials
  annotations:
    {{ if eq .Release.Namespace "prod" }}
    replicator.v1.mittwald.de/replicate-from: skypilot/oci-credentials
    {{ else }}
    replicator.v1.mittwald.de/replicate-from: skypilot-dev/oci-credentials
    {{ end }}
data: {}
