{{ if and (ne "prod" .Release.Namespace) (ne "dev" .Release.Namespace) }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  annotations:
    replicator.v1.mittwald.de/replicate-from: dev/aws-credentials
data: {}
{{ end -}}