apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  annotations:
    {{ if .eq .Release.Namespace "prod" }}
    replicator.v1.mittwald.de/replicate-from: skypilot/aws-credentials
    {{ else }}
    replicator.v1.mittwald.de/replicate-from: skypilot-dev/aws-credentials
    {{ end }}
data: {}