apiVersion: v1
kind: Secret
metadata:
  name: runpod-credentials
  annotations:
    {{ if eq .Release.Namespace "prod" }}
    replicator.v1.mittwald.de/replicate-from: skypilot/runpod-credentials
    {{ else }}
    replicator.v1.mittwald.de/replicate-from: skypilot-dev/runpod-credentials
    {{ end }}
data: {}