apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-authentik-ingress-skypilot-api"
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: skypilot-api-sa
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: authentik
        app.kubernetes.io/name: authentik
