apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: permissive-mtls-towards-skypilot-api
spec:
  mtls:
    mode: PERMISSIVE
  selector:
    matchLabels:
      app: skypilot-api